import type { AITool, Category, CategoryInfo } from './types'

export const aiTools: AITool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    slug: 'chatgpt',
    description:
      'ChatGPT is an advanced AI language model developed by OpenAI that can engage in conversational dialogue, answer questions, write content, and assist with a wide variety of tasks. It uses deep learning to produce human-like text based on the input it receives.',
    shortDescription:
      'Advanced AI chatbot for conversations, writing, and problem-solving.',
    category: 'Writing',
    pricing: 'Freemium',
    website: 'https://chat.openai.com',
    logo: '/logos/chatgpt.svg',
    features: [
      'Natural language conversations',
      'Code generation and debugging',
      'Content writing assistance',
      'Language translation',
      'Data analysis',
    ],
    useCases: [
      'Customer support automation',
      'Content creation',
      'Learning and research',
      'Programming assistance',
    ],
    rating: 4.8,
    reviewCount: 25000,
    launchDate: '2022-11-30',
    isFeatured: true,
    isNew: false,
    tags: ['chatbot', 'nlp', 'openai', 'gpt-4'],
  },
  {
    id: '2',
    name: 'Midjourney',
    slug: 'midjourney',
    description:
      'Midjourney is a generative AI program that creates images from natural language descriptions, called prompts. It is known for producing highly artistic and creative visuals that push the boundaries of AI-generated art.',
    shortDescription:
      'AI image generator creating stunning artwork from text prompts.',
    category: 'Image Generation',
    pricing: 'Paid',
    website: 'https://midjourney.com',
    logo: '/logos/midjourney.svg',
    features: [
      'Text-to-image generation',
      'Style variations',
      'Image upscaling',
      'Pan and zoom features',
      'Blend multiple images',
    ],
    useCases: [
      'Digital art creation',
      'Marketing visuals',
      'Concept art',
      'Social media content',
    ],
    rating: 4.9,
    reviewCount: 18000,
    launchDate: '2022-07-12',
    isFeatured: true,
    isNew: false,
    tags: ['art', 'images', 'creative', 'design'],
  },
  {
    id: '3',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description:
      'GitHub Copilot is an AI-powered code completion tool developed by GitHub and OpenAI. It suggests code and entire functions in real-time, right from your editor, helping developers write code faster and with less effort.',
    shortDescription:
      'AI pair programmer that suggests code as you type.',
    category: 'Code Assistant',
    pricing: 'Paid',
    website: 'https://github.com/features/copilot',
    logo: '/logos/copilot.svg',
    features: [
      'Real-time code suggestions',
      'Multi-language support',
      'IDE integration',
      'Context-aware completions',
      'Documentation generation',
    ],
    useCases: [
      'Faster development',
      'Learning new languages',
      'Boilerplate reduction',
      'Code reviews',
    ],
    rating: 4.7,
    reviewCount: 15000,
    launchDate: '2021-06-29',
    isFeatured: true,
    isNew: false,
    tags: ['coding', 'developer', 'github', 'productivity'],
  },
  {
    id: '4',
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    description:
      'DALL-E 3 is OpenAI\'s latest image generation model that creates highly detailed and accurate images from text descriptions. It excels at following complex prompts and generating images with precise text rendering.',
    shortDescription:
      'OpenAI\'s most advanced text-to-image model with superior accuracy.',
    category: 'Image Generation',
    pricing: 'Freemium',
    website: 'https://openai.com/dall-e-3',
    logo: '/logos/dalle.svg',
    features: [
      'High-fidelity image generation',
      'Accurate text rendering',
      'Complex prompt understanding',
      'Safety filters',
      'ChatGPT integration',
    ],
    useCases: [
      'Product mockups',
      'Illustration',
      'Marketing materials',
      'Educational content',
    ],
    rating: 4.8,
    reviewCount: 12000,
    launchDate: '2023-10-03',
    isFeatured: true,
    isNew: false,
    tags: ['images', 'openai', 'creative', 'art'],
  },
  {
    id: '5',
    name: 'Runway ML',
    slug: 'runway-ml',
    description:
      'Runway ML is a creative suite powered by AI that offers video editing, image generation, and various creative tools. It\'s known for its Gen-2 video generation model that can create videos from text or images.',
    shortDescription:
      'AI-powered creative suite for video generation and editing.',
    category: 'Video',
    pricing: 'Freemium',
    website: 'https://runwayml.com',
    logo: '/logos/runway.svg',
    features: [
      'Text-to-video generation',
      'Image-to-video conversion',
      'Video editing tools',
      'Background removal',
      'Motion tracking',
    ],
    useCases: [
      'Video production',
      'Film pre-visualization',
      'Social media content',
      'Advertising',
    ],
    rating: 4.6,
    reviewCount: 8000,
    launchDate: '2018-07-01',
    isFeatured: true,
    isNew: false,
    tags: ['video', 'creative', 'editing', 'gen-2'],
  },
  {
    id: '6',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description:
      'ElevenLabs is an AI voice technology company that provides realistic text-to-speech and voice cloning services. Their technology can generate natural-sounding speech in multiple languages and voices.',
    shortDescription:
      'AI voice synthesis with realistic text-to-speech and voice cloning.',
    category: 'Audio',
    pricing: 'Freemium',
    website: 'https://elevenlabs.io',
    logo: '/logos/elevenlabs.svg',
    features: [
      'Natural text-to-speech',
      'Voice cloning',
      'Multi-language support',
      'Emotion control',
      'API access',
    ],
    useCases: [
      'Audiobook production',
      'Podcast creation',
      'Video voiceovers',
      'Accessibility',
    ],
    rating: 4.7,
    reviewCount: 6500,
    launchDate: '2022-01-01',
    isFeatured: false,
    isNew: false,
    tags: ['voice', 'audio', 'tts', 'speech'],
  },
  {
    id: '7',
    name: 'Notion AI',
    slug: 'notion-ai',
    description:
      'Notion AI is an integrated AI assistant within the Notion workspace that helps users write, brainstorm, edit, and summarize content directly in their notes and documents.',
    shortDescription:
      'AI writing assistant integrated into Notion workspace.',
    category: 'Productivity',
    pricing: 'Paid',
    website: 'https://notion.so/product/ai',
    logo: '/logos/notion.svg',
    features: [
      'AI writing assistance',
      'Content summarization',
      'Translation',
      'Brainstorming',
      'Meeting notes generation',
    ],
    useCases: [
      'Note-taking',
      'Project documentation',
      'Meeting summaries',
      'Content planning',
    ],
    rating: 4.5,
    reviewCount: 9000,
    launchDate: '2023-02-22',
    isFeatured: false,
    isNew: false,
    tags: ['productivity', 'writing', 'workspace', 'notes'],
  },
  {
    id: '8',
    name: 'Jasper',
    slug: 'jasper',
    description:
      'Jasper is an AI content platform designed for marketing teams. It helps create marketing copy, blog posts, social media content, and more with brand voice consistency.',
    shortDescription:
      'AI marketing platform for generating branded content at scale.',
    category: 'Marketing',
    pricing: 'Paid',
    website: 'https://jasper.ai',
    logo: '/logos/jasper.svg',
    features: [
      'Brand voice training',
      'Marketing templates',
      'Team collaboration',
      'SEO optimization',
      'Multi-channel content',
    ],
    useCases: [
      'Blog writing',
      'Ad copy',
      'Email marketing',
      'Social media posts',
    ],
    rating: 4.4,
    reviewCount: 7500,
    launchDate: '2021-01-01',
    isFeatured: false,
    isNew: false,
    tags: ['marketing', 'content', 'copywriting', 'seo'],
  },
  {
    id: '9',
    name: 'Tableau AI',
    slug: 'tableau-ai',
    description:
      'Tableau AI brings artificial intelligence capabilities to Tableau\'s data visualization platform, enabling natural language queries, automated insights, and predictive analytics.',
    shortDescription:
      'AI-powered data visualization and business intelligence.',
    category: 'Data Analysis',
    pricing: 'Enterprise',
    website: 'https://tableau.com',
    logo: '/logos/tableau.svg',
    features: [
      'Natural language queries',
      'Automated insights',
      'Predictive analytics',
      'Smart recommendations',
      'Data storytelling',
    ],
    useCases: [
      'Business intelligence',
      'Data exploration',
      'Executive dashboards',
      'Trend analysis',
    ],
    rating: 4.6,
    reviewCount: 5000,
    launchDate: '2023-05-01',
    isFeatured: false,
    isNew: false,
    tags: ['analytics', 'visualization', 'business', 'data'],
  },
  {
    id: '10',
    name: 'Intercom Fin',
    slug: 'intercom-fin',
    description:
      'Intercom Fin is an AI-powered customer service bot that resolves customer issues instantly using your support content. It provides accurate, conversational support 24/7.',
    shortDescription:
      'AI customer support bot for instant, accurate responses.',
    category: 'Customer Support',
    pricing: 'Paid',
    website: 'https://intercom.com/fin',
    logo: '/logos/intercom.svg',
    features: [
      'Instant answers',
      'Knowledge base integration',
      'Human handoff',
      'Multi-language support',
      'Analytics dashboard',
    ],
    useCases: [
      'Customer support',
      'Help desk automation',
      'FAQ handling',
      'Lead qualification',
    ],
    rating: 4.5,
    reviewCount: 4000,
    launchDate: '2023-03-14',
    isFeatured: false,
    isNew: false,
    tags: ['support', 'chatbot', 'customer service', 'helpdesk'],
  },
  {
    id: '11',
    name: 'Duolingo Max',
    slug: 'duolingo-max',
    description:
      'Duolingo Max uses GPT-4 to provide two new features: Explain My Answer for personalized feedback and Roleplay for AI conversation practice in language learning.',
    shortDescription:
      'AI-enhanced language learning with GPT-4 powered features.',
    category: 'Education',
    pricing: 'Paid',
    website: 'https://duolingo.com',
    logo: '/logos/duolingo.svg',
    features: [
      'AI explanations',
      'Roleplay conversations',
      'Personalized feedback',
      'Adaptive learning',
      'Gamified progress',
    ],
    useCases: [
      'Language learning',
      'Conversation practice',
      'Grammar improvement',
      'Vocabulary building',
    ],
    rating: 4.7,
    reviewCount: 11000,
    launchDate: '2023-03-14',
    isFeatured: false,
    isNew: false,
    tags: ['education', 'language', 'learning', 'gpt-4'],
  },
  {
    id: '12',
    name: 'Cursor',
    slug: 'cursor',
    description:
      'Cursor is an AI-first code editor built for pair programming with AI. It features intelligent code completion, natural language editing, and codebase understanding.',
    shortDescription:
      'AI-first code editor for intelligent pair programming.',
    category: 'Code Assistant',
    pricing: 'Freemium',
    website: 'https://cursor.sh',
    logo: '/logos/cursor.svg',
    features: [
      'AI code completion',
      'Natural language editing',
      'Codebase chat',
      'Multi-file editing',
      'Terminal integration',
    ],
    useCases: [
      'Software development',
      'Code refactoring',
      'Bug fixing',
      'Learning to code',
    ],
    rating: 4.8,
    reviewCount: 6000,
    launchDate: '2023-01-01',
    isFeatured: true,
    isNew: true,
    tags: ['coding', 'editor', 'ide', 'ai-native'],
  },
  {
    id: '13',
    name: 'Claude',
    slug: 'claude',
    description:
      'Claude is an AI assistant created by Anthropic that excels at thoughtful dialogue, content creation, complex reasoning, and coding. Known for its helpfulness and harmlessness.',
    shortDescription:
      'Anthropic\'s AI assistant for thoughtful dialogue and analysis.',
    category: 'Writing',
    pricing: 'Freemium',
    website: 'https://claude.ai',
    logo: '/logos/claude.svg',
    features: [
      'Long context window',
      'Document analysis',
      'Code assistance',
      'Creative writing',
      'Research help',
    ],
    useCases: [
      'Research analysis',
      'Content creation',
      'Coding assistance',
      'Document summarization',
    ],
    rating: 4.8,
    reviewCount: 14000,
    launchDate: '2023-03-14',
    isFeatured: true,
    isNew: false,
    tags: ['chatbot', 'anthropic', 'writing', 'analysis'],
  },
  {
    id: '14',
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    description:
      'Stable Diffusion is an open-source text-to-image model that generates detailed images from text descriptions. It can run locally and offers extensive customization options.',
    shortDescription:
      'Open-source AI image generation with local deployment options.',
    category: 'Image Generation',
    pricing: 'Free',
    website: 'https://stability.ai',
    logo: '/logos/stability.svg',
    features: [
      'Text-to-image generation',
      'Image-to-image editing',
      'Inpainting',
      'Local deployment',
      'Fine-tuning support',
    ],
    useCases: [
      'Digital art',
      'Photo editing',
      'Game assets',
      'Research',
    ],
    rating: 4.6,
    reviewCount: 20000,
    launchDate: '2022-08-22',
    isFeatured: false,
    isNew: false,
    tags: ['open-source', 'images', 'local', 'customizable'],
  },
  {
    id: '15',
    name: 'Synthesia',
    slug: 'synthesia',
    description:
      'Synthesia is an AI video generation platform that creates professional videos with AI avatars. Simply type your script and choose an avatar to generate studio-quality videos.',
    shortDescription:
      'AI video platform with realistic digital avatars.',
    category: 'Video',
    pricing: 'Paid',
    website: 'https://synthesia.io',
    logo: '/logos/synthesia.svg',
    features: [
      'AI avatars',
      'Multi-language videos',
      'Custom avatar creation',
      'Templates library',
      'Brand customization',
    ],
    useCases: [
      'Training videos',
      'Marketing content',
      'Internal communications',
      'Product demos',
    ],
    rating: 4.5,
    reviewCount: 5500,
    launchDate: '2017-01-01',
    isFeatured: false,
    isNew: false,
    tags: ['video', 'avatars', 'enterprise', 'training'],
  },
  {
    id: '16',
    name: 'Grammarly',
    slug: 'grammarly',
    description:
      'Grammarly is an AI-powered writing assistant that helps with grammar, spelling, punctuation, clarity, and tone. It now includes generative AI features for content creation.',
    shortDescription:
      'AI writing assistant for grammar, clarity, and content generation.',
    category: 'Writing',
    pricing: 'Freemium',
    website: 'https://grammarly.com',
    logo: '/logos/grammarly.svg',
    features: [
      'Grammar checking',
      'Tone detection',
      'AI content generation',
      'Plagiarism detection',
      'Style suggestions',
    ],
    useCases: [
      'Professional writing',
      'Academic papers',
      'Email composition',
      'Content editing',
    ],
    rating: 4.6,
    reviewCount: 30000,
    launchDate: '2009-07-01',
    isFeatured: false,
    isNew: false,
    tags: ['writing', 'grammar', 'editing', 'productivity'],
  },
  {
    id: '17',
    name: 'Perplexity',
    slug: 'perplexity',
    description:
      'Perplexity is an AI-powered search engine that provides direct answers with citations. It combines large language models with real-time web search for accurate, sourced information.',
    shortDescription:
      'AI search engine with cited answers and real-time information.',
    category: 'Productivity',
    pricing: 'Freemium',
    website: 'https://perplexity.ai',
    logo: '/logos/perplexity.svg',
    features: [
      'AI-powered search',
      'Source citations',
      'Follow-up questions',
      'File analysis',
      'Collections',
    ],
    useCases: [
      'Research',
      'Fact-checking',
      'Learning',
      'News monitoring',
    ],
    rating: 4.7,
    reviewCount: 8500,
    launchDate: '2022-08-01',
    isFeatured: true,
    isNew: false,
    tags: ['search', 'research', 'citations', 'ai-native'],
  },
  {
    id: '18',
    name: 'Copy.ai',
    slug: 'copy-ai',
    description:
      'Copy.ai is an AI-powered copywriting tool that generates marketing copy, blog posts, emails, and social media content. It offers templates for various content types.',
    shortDescription:
      'AI copywriting tool for marketing and sales content.',
    category: 'Marketing',
    pricing: 'Freemium',
    website: 'https://copy.ai',
    logo: '/logos/copyai.svg',
    features: [
      'Marketing copy generation',
      'Blog post writing',
      'Email templates',
      'Social media content',
      'Workflow automation',
    ],
    useCases: [
      'Ad copy creation',
      'Blog writing',
      'Product descriptions',
      'Sales emails',
    ],
    rating: 4.3,
    reviewCount: 6000,
    launchDate: '2020-10-01',
    isFeatured: false,
    isNew: false,
    tags: ['copywriting', 'marketing', 'content', 'automation'],
  },
  {
    id: '19',
    name: 'Suno',
    slug: 'suno',
    description:
      'Suno is an AI music generation platform that creates original songs with vocals, instrumentals, and lyrics from text prompts. It can generate full songs in various genres.',
    shortDescription:
      'AI music generator creating full songs with vocals and instruments.',
    category: 'Audio',
    pricing: 'Freemium',
    website: 'https://suno.ai',
    logo: '/logos/suno.svg',
    features: [
      'Full song generation',
      'Vocal synthesis',
      'Multiple genres',
      'Lyrics generation',
      'Style customization',
    ],
    useCases: [
      'Music production',
      'Content creation',
      'Podcasts',
      'Social media',
    ],
    rating: 4.6,
    reviewCount: 4500,
    launchDate: '2023-09-01',
    isFeatured: true,
    isNew: true,
    tags: ['music', 'audio', 'creative', 'vocals'],
  },
  {
    id: '20',
    name: 'Replit AI',
    slug: 'replit-ai',
    description:
      'Replit AI provides AI-powered coding assistance within the Replit online IDE. It includes code completion, explanation, debugging, and an AI chat for coding questions.',
    shortDescription:
      'AI coding assistant in Replit\'s browser-based IDE.',
    category: 'Code Assistant',
    pricing: 'Freemium',
    website: 'https://replit.com',
    logo: '/logos/replit.svg',
    features: [
      'Code completion',
      'Code explanation',
      'Debugging help',
      'AI chat',
      'Cloud deployment',
    ],
    useCases: [
      'Learning to code',
      'Rapid prototyping',
      'Collaborative coding',
      'Web development',
    ],
    rating: 4.5,
    reviewCount: 7000,
    launchDate: '2023-04-01',
    isFeatured: false,
    isNew: false,
    tags: ['coding', 'ide', 'learning', 'cloud'],
  },
  {
    id: '21',
    name: 'Descript',
    slug: 'descript',
    description:
      'Descript is an all-in-one video and audio editing platform with AI-powered features including transcription, overdub (voice cloning), and text-based video editing.',
    shortDescription:
      'AI-powered video and audio editing with text-based workflow.',
    category: 'Video',
    pricing: 'Freemium',
    website: 'https://descript.com',
    logo: '/logos/descript.svg',
    features: [
      'Text-based editing',
      'AI transcription',
      'Voice cloning (Overdub)',
      'Screen recording',
      'Filler word removal',
    ],
    useCases: [
      'Podcast editing',
      'Video production',
      'Content repurposing',
      'Transcription',
    ],
    rating: 4.6,
    reviewCount: 5200,
    launchDate: '2017-01-01',
    isFeatured: false,
    isNew: false,
    tags: ['video', 'audio', 'editing', 'transcription'],
  },
  {
    id: '22',
    name: 'Khan Academy Khanmigo',
    slug: 'khanmigo',
    description:
      'Khanmigo is Khan Academy\'s AI tutor powered by GPT-4. It provides personalized tutoring, helps with homework, and guides students through problems without giving direct answers.',
    shortDescription:
      'AI tutor for personalized learning and homework help.',
    category: 'Education',
    pricing: 'Paid',
    website: 'https://khanacademy.org/khan-labs',
    logo: '/logos/khanmigo.svg',
    features: [
      'Personalized tutoring',
      'Socratic method',
      'Progress tracking',
      'Multiple subjects',
      'Teacher tools',
    ],
    useCases: [
      'Homework help',
      'Test preparation',
      'Concept learning',
      'Writing assistance',
    ],
    rating: 4.6,
    reviewCount: 3500,
    launchDate: '2023-03-01',
    isFeatured: false,
    isNew: false,
    tags: ['education', 'tutoring', 'learning', 'students'],
  },
  {
    id: '23',
    name: 'Otter.ai',
    slug: 'otter-ai',
    description:
      'Otter.ai is an AI meeting assistant that provides real-time transcription, automated meeting notes, and action item extraction for meetings and conversations.',
    shortDescription:
      'AI meeting assistant with transcription and note-taking.',
    category: 'Productivity',
    pricing: 'Freemium',
    website: 'https://otter.ai',
    logo: '/logos/otter.svg',
    features: [
      'Real-time transcription',
      'Meeting summaries',
      'Action item extraction',
      'Speaker identification',
      'Integration with Zoom/Meet',
    ],
    useCases: [
      'Meeting notes',
      'Interview transcription',
      'Lecture recording',
      'Accessibility',
    ],
    rating: 4.4,
    reviewCount: 8000,
    launchDate: '2016-01-01',
    isFeatured: false,
    isNew: false,
    tags: ['meetings', 'transcription', 'productivity', 'notes'],
  },
  {
    id: '24',
    name: 'Leonardo AI',
    slug: 'leonardo-ai',
    description:
      'Leonardo AI is an image generation platform focused on game assets, concept art, and creative content. It offers fine-tuned models and training capabilities.',
    shortDescription:
      'AI image generation for game assets and creative content.',
    category: 'Image Generation',
    pricing: 'Freemium',
    website: 'https://leonardo.ai',
    logo: '/logos/leonardo.svg',
    features: [
      'Image generation',
      'Model fine-tuning',
      'Canvas editing',
      'Texture generation',
      'Real-time generation',
    ],
    useCases: [
      'Game development',
      'Concept art',
      'Character design',
      'Asset creation',
    ],
    rating: 4.5,
    reviewCount: 6500,
    launchDate: '2022-12-01',
    isFeatured: false,
    isNew: false,
    tags: ['images', 'gaming', 'art', 'assets'],
  },
]

export const categories: CategoryInfo[] = [
  {
    name: 'Writing',
    slug: 'writing',
    description: 'AI tools for content creation, copywriting, and text generation.',
    count: aiTools.filter((t) => t.category === 'Writing').length,
  },
  {
    name: 'Image Generation',
    slug: 'image-generation',
    description: 'Create stunning visuals, artwork, and graphics with AI.',
    count: aiTools.filter((t) => t.category === 'Image Generation').length,
  },
  {
    name: 'Code Assistant',
    slug: 'code-assistant',
    description: 'AI-powered coding helpers and development tools.',
    count: aiTools.filter((t) => t.category === 'Code Assistant').length,
  },
  {
    name: 'Video',
    slug: 'video',
    description: 'Generate and edit videos with artificial intelligence.',
    count: aiTools.filter((t) => t.category === 'Video').length,
  },
  {
    name: 'Audio',
    slug: 'audio',
    description: 'AI tools for voice, music, and sound generation.',
    count: aiTools.filter((t) => t.category === 'Audio').length,
  },
  {
    name: 'Productivity',
    slug: 'productivity',
    description: 'Boost your workflow with AI-powered productivity tools.',
    count: aiTools.filter((t) => t.category === 'Productivity').length,
  },
  {
    name: 'Marketing',
    slug: 'marketing',
    description: 'AI tools for marketing automation and content.',
    count: aiTools.filter((t) => t.category === 'Marketing').length,
  },
  {
    name: 'Data Analysis',
    slug: 'data-analysis',
    description: 'Analyze and visualize data with AI assistance.',
    count: aiTools.filter((t) => t.category === 'Data Analysis').length,
  },
  {
    name: 'Customer Support',
    slug: 'customer-support',
    description: 'AI chatbots and support automation tools.',
    count: aiTools.filter((t) => t.category === 'Customer Support').length,
  },
  {
    name: 'Education',
    slug: 'education',
    description: 'AI tutors and learning assistance tools.',
    count: aiTools.filter((t) => t.category === 'Education').length,
  },
]

export function getToolBySlug(slug: string): AITool | undefined {
  return aiTools.find((tool) => tool.slug === slug)
}

export function getToolsByCategory(category: Category): AITool[] {
  return aiTools.filter((tool) => tool.category === category)
}

export function getFeaturedTools(): AITool[] {
  return aiTools.filter((tool) => tool.isFeatured)
}

export function getNewTools(): AITool[] {
  return aiTools.filter((tool) => tool.isNew)
}

export function getFreeTools(): AITool[] {
  return aiTools.filter((tool) => tool.pricing === 'Free' || tool.pricing === 'Freemium')
}

export function searchTools(query: string): AITool[] {
  const lowerQuery = query.toLowerCase()
  return aiTools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.category.toLowerCase().includes(lowerQuery) ||
      tool.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  )
}

export function getCategoryBySlug(slug: string): CategoryInfo | undefined {
  return categories.find((cat) => cat.slug === slug)
}
